import { writeFileSync } from "node:fs";
import { getCliVersion } from "../lib/update";
import { HEADER_SEPARATOR } from "./constants";
import type { TemplateOptions } from "./types";

/**
 * Derive .env filename from template filename
 * .env.tpl -> .env
 * .env.local.tpl -> .env.local
 */
function deriveEnvFileName(templateFileName: string): string {
    if (templateFileName.endsWith(".tpl")) {
        return templateFileName.slice(0, -4);
    }
    return templateFileName;
}

/**
 * Derive template filename from .env filename
 * .env -> .env.tpl
 * .env.local -> .env.local.tpl
 */
function deriveTemplateFileName(envFileName: string): string {
    return `${envFileName}.tpl`;
}

/**
 * Format timestamp for header display
 */
function formatTimestamp(): string {
    return new Date()
        .toISOString()
        .replace("T", " ")
        .replace(/\.\d{3}Z$/, " UTC");
}

/**
 * Generate header for .env.tpl template files
 */
export function generateTemplateHeader(templateFileName: string): string[] {
    const envFileName = deriveEnvFileName(templateFileName);
    return [
        HEADER_SEPARATOR,
        `#  ${templateFileName} — 1Password Secret References`,
        "#",
        "#  This template contains references to secrets stored in 1Password.",
        "#  The actual values are not stored here — only secret references.",
        "#",
        `#  To generate ${envFileName} with real values:`,
        `#    op2env ${templateFileName}`,
        "#",
        "#  To run a command with secrets injected:",
        `#    op run --env-file ${templateFileName} -- npm start`,
        "#",
        `#  Pushed: ${formatTimestamp()}`,
        `#  Generated by env2op v${getCliVersion()}`,
        "#  https://github.com/tolgamorf/env2op-cli",
        HEADER_SEPARATOR,
        "",
    ];
}

/**
 * Generate header for .env files (after pulling from 1Password)
 */
export function generateEnvHeader(envFileName: string): string[] {
    const templateFileName = deriveTemplateFileName(envFileName);
    return [
        HEADER_SEPARATOR,
        `#  ${envFileName} — Environment Variables`,
        "#",
        "#  WARNING: This file contains sensitive values. Do not commit to git!",
        "#",
        `#  To push updates to 1Password and generate ${templateFileName}:`,
        `#    env2op ${envFileName} <vault> "<item_name>"`,
        "#",
        `#  Pulled: ${formatTimestamp()}`,
        `#  Generated by op2env v${getCliVersion()}`,
        "#  https://github.com/tolgamorf/env2op-cli",
        HEADER_SEPARATOR,
        "",
        "",
    ];
}

/**
 * Generate op:// reference template content
 *
 * Format: KEY=op://vault/item/field
 *
 * This template can be used with:
 * - `op2env template.tpl` to generate .env
 * - `op run --env-file template.tpl -- command`
 */
export function generateTemplateContent(options: TemplateOptions, templateFileName: string): string {
    const { vaultId, itemId, lines: envLines, fieldIds } = options;

    const outputLines: string[] = generateTemplateHeader(templateFileName);

    for (const line of envLines) {
        switch (line.type) {
            case "empty":
                outputLines.push("");
                break;
            case "comment":
                outputLines.push(line.content);
                break;
            case "variable": {
                const fieldId = fieldIds[line.key] ?? line.key;
                outputLines.push(`${line.key}=op://${vaultId}/${itemId}/${fieldId}`);
                break;
            }
        }
    }

    return `${outputLines.join("\n")}\n`;
}

/**
 * Write template to file
 */
export function writeTemplate(content: string, outputPath: string): void {
    writeFileSync(outputPath, content, "utf-8");
}

/**
 * Generate usage instructions for display
 */
export function generateUsageInstructions(templatePath: string): string {
    return ["Usage:", `  op2env ${templatePath}`, `  op run --env-file ${templatePath} -- npm start`].join("\n");
}
