import { writeFileSync } from "node:fs";
import type { TemplateOptions } from "./types";

/**
 * Generate op:// reference template content
 *
 * Format: KEY=op://vault/item/field
 *
 * This template can be used with:
 * - `op inject -i template.tpl -o .env`
 * - `op run --env-file template.tpl -- command`
 */
export function generateTemplateContent(options: TemplateOptions): string {
	const { vault, itemTitle, variables } = options;

	const lines: string[] = [
		"# Generated by env2op",
		"# https://github.com/tolgamorf/env2op",
		"#",
		"# Usage:",
		`#   op inject -i ${getTemplateName(options)} -o .env`,
		`#   op run --env-file ${getTemplateName(options)} -- npm start`,
		"",
	];

	for (const { key, comment } of variables) {
		if (comment) {
			lines.push(`# ${comment}`);
		}
		lines.push(`${key}=op://${vault}/${itemTitle}/${key}`);
	}

	return `${lines.join("\n")}\n`;
}

/**
 * Get the template filename based on the source file
 */
function getTemplateName(options: TemplateOptions): string {
	return `${options.itemTitle.toLowerCase().replace(/\s+/g, "-")}.tpl`;
}

/**
 * Write template to file
 */
export function writeTemplate(content: string, outputPath: string): void {
	writeFileSync(outputPath, content, "utf-8");
}

/**
 * Generate usage instructions for display
 */
export function generateUsageInstructions(templatePath: string): string {
	return [
		"",
		"Usage:",
		`  op inject -i ${templatePath} -o .env`,
		`  op run --env-file ${templatePath} -- npm start`,
	].join("\n");
}
