import { writeFileSync } from "node:fs";
import pkg from "../../package.json";
import type { TemplateOptions } from "./types";

/**
 * Generate op:// reference template content
 *
 * Format: KEY=op://vault/item/field
 *
 * This template can be used with:
 * - `op inject -i template.tpl -o .env`
 * - `op run --env-file template.tpl -- command`
 */
export function generateTemplateContent(options: TemplateOptions, templateFileName: string): string {
    const { vaultId, itemId, lines: envLines, fieldIds } = options;

    const outputLines: string[] = [
        `# Generated by env2op v${pkg.version}`,
        "# https://github.com/tolgamorf/env2op-cli#readme",
        "#",
        "# Usage:",
        `#   op2env ${templateFileName}`,
        `#   op run --env-file ${templateFileName} -- npm start`,
        "",
    ];

    for (const line of envLines) {
        switch (line.type) {
            case "empty":
                outputLines.push("");
                break;
            case "comment":
                outputLines.push(line.content);
                break;
            case "variable": {
                const fieldId = fieldIds[line.key] ?? line.key;
                outputLines.push(`${line.key}=op://${vaultId}/${itemId}/${fieldId}`);
                break;
            }
        }
    }

    return `${outputLines.join("\n")}\n`;
}

/**
 * Write template to file
 */
export function writeTemplate(content: string, outputPath: string): void {
    writeFileSync(outputPath, content, "utf-8");
}

/**
 * Generate usage instructions for display
 */
export function generateUsageInstructions(templatePath: string): string {
    return ["", "Usage:", `  op2env ${templatePath}`, `  op run --env-file ${templatePath} -- npm start`].join("\n");
}
