Output env2op-demo.gif

Set FontSize 20
Set Width 1200
Set Height 800
Set TypingSpeed 85ms

Type "env2op .env 'tolgamorf' 'My App .env' --force" Sleep 400ms Enter
Hide
Sleep 5s
Show
Sleep 14s

Type "cat .env.tpl" Sleep 400ms Enter
Sleep 6s

Type "clear" Sleep 300ms Enter
Sleep 1s

Type "op2env .env.tpl --output .env.local" Sleep 400ms Enter
Sleep 2s
Enter
Sleep 3s

Type "cat .env.local" Sleep 400ms Enter
Sleep 8s

Type "clear" Sleep 300ms Enter
Sleep 2s
