import { describe, expect, test } from "bun:test";
import { generateTemplateContent, generateUsageInstructions } from "../../src/core/template-generator";
import type { TemplateOptions } from "../../src/core/types";

describe("generateTemplateContent", () => {
    const createOptions = (overrides: Partial<TemplateOptions> = {}): TemplateOptions => ({
        vaultId: "vault123",
        itemId: "item456",
        variables: [
            { key: "KEY1", value: "value1", line: 1 },
            { key: "KEY2", value: "value2", line: 2 },
        ],
        lines: [
            { type: "variable", key: "KEY1", value: "value1" },
            { type: "variable", key: "KEY2", value: "value2" },
        ],
        fieldIds: {
            KEY1: "field1",
            KEY2: "field2",
        },
        ...overrides,
    });

    test("generates correct op:// references", () => {
        const options = createOptions();
        const content = generateTemplateContent(options, ".env.tpl");

        expect(content).toContain("KEY1=op://vault123/item456/field1");
        expect(content).toContain("KEY2=op://vault123/item456/field2");
    });

    test("uses field IDs in references", () => {
        const options = createOptions({
            fieldIds: {
                KEY1: "abc123",
                KEY2: "def456",
            },
        });
        const content = generateTemplateContent(options, ".env.tpl");

        expect(content).toContain("op://vault123/item456/abc123");
        expect(content).toContain("op://vault123/item456/def456");
    });

    test("falls back to key name when fieldId is missing", () => {
        const options = createOptions({
            fieldIds: {}, // No field IDs
        });
        const content = generateTemplateContent(options, ".env.tpl");

        // Should use key name as fallback
        expect(content).toContain("KEY1=op://vault123/item456/KEY1");
    });

    test("includes version header", () => {
        const options = createOptions();
        const content = generateTemplateContent(options, ".env.tpl");

        expect(content).toMatch(/# Generated by env2op v[\d.]+/);
    });

    test("includes repository link", () => {
        const options = createOptions();
        const content = generateTemplateContent(options, ".env.tpl");

        expect(content).toContain("https://github.com/tolgamorf/env2op-cli");
    });

    test("includes usage instructions with template filename", () => {
        const options = createOptions();
        const content = generateTemplateContent(options, "secrets.tpl");

        expect(content).toContain("op2env secrets.tpl");
        expect(content).toContain("op run --env-file secrets.tpl");
    });

    test("preserves empty lines", () => {
        const options = createOptions({
            lines: [
                { type: "variable", key: "KEY1", value: "value1" },
                { type: "empty" },
                { type: "variable", key: "KEY2", value: "value2" },
            ],
        });
        const content = generateTemplateContent(options, ".env.tpl");
        const lines = content.split("\n");

        // Find the empty line between variables (after header)
        const key1Index = lines.findIndex((l) => l.includes("KEY1="));
        const key2Index = lines.findIndex((l) => l.includes("KEY2="));

        // There should be an empty line between them
        expect(key2Index - key1Index).toBe(2);
    });

    test("preserves comments", () => {
        const options = createOptions({
            lines: [
                { type: "comment", content: "# Database config" },
                { type: "variable", key: "KEY1", value: "value1" },
            ],
        });
        const content = generateTemplateContent(options, ".env.tpl");

        expect(content).toContain("# Database config");
    });

    test("ends with newline", () => {
        const options = createOptions();
        const content = generateTemplateContent(options, ".env.tpl");

        expect(content.endsWith("\n")).toBe(true);
    });
});

describe("generateUsageInstructions", () => {
    test("includes op2env command", () => {
        const instructions = generateUsageInstructions(".env.tpl");
        expect(instructions).toContain("op2env .env.tpl");
    });

    test("includes op run command", () => {
        const instructions = generateUsageInstructions(".env.tpl");
        expect(instructions).toContain("op run --env-file .env.tpl");
    });

    test("uses provided template path", () => {
        const instructions = generateUsageInstructions("/path/to/secrets.tpl");
        expect(instructions).toContain("op2env /path/to/secrets.tpl");
    });
});
